name: sdc_env
channels:
  - defaults
dependencies:
  - python=3.9
  - torchvision
  - pytorch=1
  - pillow
  - matplotlib=3.6
  - scikit-learn
  - ipykernel 
  - tqdm
  - pandas
  - numpy
  - conda-forge::mayavi
  - pip:
    - ipywidgets
    - albumentations
    - dask
    - wandb
    - SciencePlots
    - fitter
    - scikit-image
    - SimpleITK
    - tikzplotlib
    - pyradiomics
    - antspyx